module.exports = {
  apps: [
    {
      name: 'pump-investments-web',
      script: 'npm',
      args: 'start',
      cwd: '/home/hendo420/pumpInvestments/v0-pump-investments',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      error_file: './logs/web-error.log',
      out_file: './logs/web-out.log',
      log_file: './logs/web-combined.log',
      time: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      max_size: '10M',
      retain: 5,
      compress: true,
    },
    {
      name: 'pump-investments-ingest',
      script: 'npm',
      args: 'run ingest',
      cwd: '/home/hendo420/pumpInvestments/v0-pump-investments',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
      },
      error_file: './logs/ingest-error.log',
      out_file: './logs/ingest-out.log',
      log_file: './logs/ingest-combined.log',
      time: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      max_size: '10M',
      retain: 5,
      compress: true,
    },
  ],
};

